 services:

  postgresql:
    image: postgres:14-alpine
    container_name: query_service
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mh_service
      - PGDATA=/data/postgres




